wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.15
    cli_version: 0.15.3
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689858597.057469
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.8.15
      5: 0.15.3
      6: 4.27.4
      8:
      - 5
